src/Entity/Evaluation.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EvaluationRepository")
 */
class Evaluation
{
    const STATUTES = [
        0 => 'to do',
        1 => 'done',
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $position;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $candidate;

    /**
     * @var boolean
     *
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Question")
     */
    private $questions;

    /**
     * @var Answer[]
     *
     * @ORM\OneToMany(targetEntity="App\Entity\Answer", mappedBy="evaluation", cascade={"persist", "remove"})
     */
    private $answers;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->status = false;
        $this->questions = new ArrayCollection();
        $this->answers = new ArrayCollection();
    }

    public function getScore()
    {
        $score = 0;
        foreach ($this->answers as $answer) {
            $score += $answer->getValue();
        }

        return $score;
    }

    public function getStatusLabel(): string
    {
        return self::STATUTES[$this->status];
    }

    public function getId()
    {
        return $this->id;
    }

    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getCandidate(): ?string
    {
        return $this->candidate;
    }

    public function setCandidate(string $candidate): self
    {
        $this->candidate = $candidate;

        return $this;
    }

    public function getStatus(): bool
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection|Question[]
     */
    public function getQuestions(): Collection
    {
        return $this->questions;
    }

    public function addQuestion(Question $question): self
    {
        if (!$this->questions->contains($question)) {
            $this->questions[] = $question;
        }

        return $this;
    }

    public function removeQuestion(Question $question): self
    {
        if ($this->questions->contains($question)) {
            $this->questions->removeElement($question);
        }

        return $this;
    }

    /**
     * @return Collection|Answer[]
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answers->contains($answer)) {
            $this->answers->removeElement($answer);
        }

        return $this;
    }

    public function clearAnswers(): self
    {
        foreach ($this->answers as $answer) {
            $this->removeAnswer($answer);
        }

        return $this;
    }
}

src/Form/EvaluationType.php
<?php

namespace App\Form;

use App\Entity\Evaluation;
use App\Entity\Question;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EvaluationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('candidate')
            ->add('questions', null, [
                'expanded' => true,
            ])
//            ->add('questions', EntityType::class, [
//                'class' => Question::class,
//                'mapped' => false,
//                'multiple' => true,
//                'expanded' => true,
//            ])
            ->add('save', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Evaluation::class,
        ));
    }
}

src/Controller/Back/CategoryController.php
<?php

namespace App\Controller\Back;

use App\Entity\Category;
use App\Form\CategoryType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = $this->getDoctrine()->getRepository('App:Category')->findAll();

        return $this->render('back/category/index.html.twig', [
            'categories' => $categories,
        ]);
    }

    public function create(Request $request)
    {
        $entityManager = $this->getDoctrine()->getManager();

        $category = new Category();
        $form = $this->createForm(CategoryType::class, $category);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
             $entityManager->persist($category);
             $entityManager->flush();

            return $this->redirectToRoute('category');
        }


        return $this->render('back/category/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    public function update(Request $request, Category $category)
    {
        $entityManager = $this->getDoctrine()->getManager();

        $form = $this->createForm(CategoryType::class, $category);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($category);
            $entityManager->flush();

            return $this->redirectToRoute('category');
        }


        return $this->render('back/category/update.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    public function delete(Request $request, Category $category)
    {
        $entityManager = $this->getDoctrine()->getManager();

        $entityManager->remove($category);
        $entityManager->flush();

        return $this->redirectToRoute('category');
    }
}

src/Controller/Back/DefaultController.php
<?php

namespace App\Controller\Back;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class DefaultController extends Controller
{
    public function index()
    {
        return $this->render('back/index.html.twig');
    }
}

src/Controller/Back/EvaluationController.php
<?php

namespace App\Controller\Back;

use App\Entity\Answer;
use App\Entity\Evaluation;
use App\Form\EvaluationType;
use App\Form\RunEvaluationType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class EvaluationController extends Controller
{
    public function index()
    {
        $evaluations = $this->getDoctrine()->getRepository('App:Evaluation')->findAll();

        return $this->render('back/evaluation/index.html.twig', [
            'evaluations' => $evaluations,
        ]);
    }

    public function create(Request $request)
    {
        $entityManager = $this->getDoctrine()->getManager();

        $evaluation = new Evaluation();
        $form = $this->createForm(EvaluationType::class, $evaluation);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($evaluation);
            $entityManager->flush();

            return $this->redirectToRoute('evaluation');
        }


        return $this->render('back/evaluation/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    public function update(Request $request, Evaluation $evaluation)
    {
        $entityManager = $this->getDoctrine()->getManager();

        $form = $this->createForm(EvaluationType::class, $evaluation);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($evaluation);
            $entityManager->flush();

            return $this->redirectToRoute('evaluation');
        }


        return $this->render('back/evaluation/update.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    public function delete(Request $request, Evaluation $evaluation)
    {
        $entityManager = $this->getDoctrine()->getManager();

        $entityManager->remove($evaluation);
        $entityManager->flush();

        return $this->redirectToRoute('evaluation');
    }

    public function print(Evaluation $evaluation)
    {
        return $this->render('back/evaluation/print.html.twig', [
            'evaluation' => $evaluation,
        ]);
    }

    public function run(Request $request, Evaluation $evaluation)
    {
        $entityManager = $this->getDoctrine()->getManager();

        $evaluation->clearAnswers();

        foreach ($evaluation->getQuestions() as $question) {
            $answer = (new Answer())
                ->setQuestion($question)
                ->setEvaluation($evaluation)
            ;
            $evaluation->addAnswer($answer);
        }

        $form = $this->createForm(RunEvaluationType::class, $evaluation);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $evaluation->setStatus(true);
            foreach ($evaluation->getQuestions() as $question) {
                $answer = (new Answer())
                    ->setQuestion($question)
                    ->setEvaluation($evaluation)
                    ->setValue($request->request->get('score')[$question->getId()])
                ;
                $evaluation->addAnswer($answer);
            }

            $entityManager->flush();

            return $this->redirectToRoute('evaluation');
        }


        return $this->render('back/evaluation/run.html.twig', [
            'form' => $form->createView(),
//            'evaluation' => $evaluation,
        ]);
    }
}

src/Controller/Back/QuestionController.php
<?php

namespace App\Controller\Back;

use App\Entity\Question;
use App\Form\QuestionType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class QuestionController extends Controller
{
    public function index()
    {
        $questions = $this->getDoctrine()->getRepository('App:Question')->findAll();

        return $this->render('back/question/index.html.twig', [
            'questions' => $questions,
        ]);
    }

    public function create(Request $request)
    {
        $entityManager = $this->getDoctrine()->getManager();

        $question = new Question();
        $form = $this->createForm(QuestionType::class, $question);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
             $entityManager->persist($question);
             $entityManager->flush();

            return $this->redirectToRoute('question');
        }


        return $this->render('back/question/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    public function update(Request $request, Question $question)
    {
        $entityManager = $this->getDoctrine()->getManager();

        $form = $this->createForm(QuestionType::class, $question);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($question);
            $entityManager->flush();

            return $this->redirectToRoute('question');
        }


        return $this->render('back/question/update.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    public function delete(Request $request, Question $question)
    {
        $entityManager = $this->getDoctrine()->getManager();

        $entityManager->remove($question);
        $entityManager->flush();

        return $this->redirectToRoute('question');
    }
}

templates/back/evaluation/create.html.twig
{% extends 'back/base.html.twig' %}

{% block body %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Create evaluation</h1>
    </div>

    {% include 'back/evaluation/form.html.twig' %}
{% endblock body %}

templates/back/evaluation/form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
{{ form_end(form) }}

templates/back/evaluation/index.html.twig
{% extends 'back/base.html.twig' %}

{% block body %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Evaluations</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group mr-2">
                <a href="{{ path('evaluation.create') }}" class="btn btn-outline-secondary">Create</a>
            </div>
        </div>
    </div>

    {% if evaluations is not empty %}
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Candidate</th>
                <th>Position</th>
                <th>Score</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for evaluation in evaluations %}
            <tr>
                <td>{{ evaluation.id }}</td>
                <td>{{ evaluation.candidate }}</td>
                <td>{{ evaluation.position }}</td>
                <td>{{ evaluation.score }}</td>
                <td><span class="badge badge-pill {% if evaluation.status == true %}badge-success{% else %}badge-warning{% endif %}">{{ evaluation.statusLabel }}</span></td>
                <td>
                    <span data-feather="edit"></span> <a href="{{ path('evaluation.update', {id: evaluation.id}) }}">update</a>&nbsp; &nbsp;
                    <span data-feather="trash"></span> <a href="{{ path('evaluation.delete', {id: evaluation.id}) }}">delete</a>&nbsp; &nbsp;
                    <span data-feather="printer"></span> <a href="{{ path('evaluation.print', {id: evaluation.id}) }}">print</a>&nbsp; &nbsp;
                    <span data-feather="play"></span> <a href="{{ path('evaluation.run', {id: evaluation.id}) }}">run</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
        No data yet.
    {% endif %}

{% endblock body %}

templates/back/evaluation/print.html.twig
{% extends 'back/base-print.html.twig' %}

{% block body %}
    <h1>{{ evaluation.candidate }}, {{ "now" | date('d/m/Y') }}</h1>

    {% for question in evaluation.questions %}
        <h2>{{ question.label }}</h2>

        <div class="btn-group" role="group">
            <button type="button" class="btn btn-lg btn-default">1</button>
            <button type="button" class="btn btn-lg btn-default">2</button>
            <button type="button" class="btn btn-lg btn-default">3</button>
        </div>
    {% endfor %}
{% endblock body %}

templates/back/evaluation/run.html.twig
{% extends 'back/base.html.twig' %}

{% block body %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Run evaluation</h1>
    </div>

    {{ form_start(form) }}

        {% for answer in form.vars.data.answers %}
            <div class="form-group">
                <label class="form-control-label">{{ answer.question.label }}</label>

                <div>
                    <div class="btn-group btn-group-toggle" data-toggle="buttons">
                        <label class="btn btn-secondary">
                            <input type="radio" name="score[{{ answer.question.id }}]" autocomplete="off" value="1"> niveau 1
                        </label>
                        <label class="btn btn-secondary">
                            <input type="radio" name="score[{{ answer.question.id }}]" autocomplete="off" value="2"> niveau 2
                        </label>
                        <label class="btn btn-secondary">
                            <input type="radio" name="score[{{ answer.question.id }}]" autocomplete="off" value="3"> niveau 3
                        </label>
                    </div>
                </div>
            </div>
        {% endfor %}
    {{ form_end(form) }}

    {#<form method="post">#}
    {#{% for answer in evaluation.answers %}#}
        {#<div class="form-group">#}
            {#<label class="form-control-label">{{ answer.question.label }}</label>#}

            {#<div>#}
                {#<div class="btn-group btn-group-toggle" data-toggle="buttons">#}
                    {#<label class="btn btn-secondary">#}
                        {#<input type="radio" name="score" autocomplete="off" value="1"> niveau 1#}
                    {#</label>#}
                    {#<label class="btn btn-secondary">#}
                        {#<input type="radio" name="score" autocomplete="off" value="2"> niveau 2#}
                    {#</label>#}
                    {#<label class="btn btn-secondary">#}
                        {#<input type="radio" name="score" autocomplete="off" value="3"> niveau 3#}
                    {#</label>#}
                {#</div>#}
            {#</div>#}
        {#</div>#}
    {#{% endfor %}#}

        {#<div class="form-group">#}
            {#<button type="submit" class="btn btn-default">Submit</button>#}
        {#</div>#}
    {#</form>#}
{% endblock body %}

templates/back/evaluation/update.html.twig
{% extends 'back/base.html.twig' %}

{% block body %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Update evaluation</h1>
    </div>

    {% include 'back/evaluation/form.html.twig' %}
{% endblock body %}